export const DATAARR           = "DATAARR"
export const SELECTED_LANGUAGE = "SELECTED_LANGUAGE"
export const ISTRUE            = "ISTRUE"
export const NAME              = "NAME"
export const LIBS              = "LIBS"
export const REMOVE_LIBS       = "REMOVE_LIBS"
